name: Coveralls

on:
  push:
    branches:
      - main

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Install coverlet
      run: dotnet tool install --global coverlet.console

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test with coverage
      run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      env:
        NUGET_XMLDOC_MODE: skip # Skip generating XML documentation files if not needed

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fail-on-error: false
